<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<gradle-project-properties>
  <!--DO NOT EDIT THIS FILE! - Used by the Gradle plugin of NetBeans.-->
  <license-header>
    <name>Apache 2.0</name>
    <template>LICENSE.txt</template>
    <property name="organization">Google Inc.</property>
  </license-header>
</gradle-project-properties>
